---
galaxy_info:
  author: Robin Andeer
  description: >
    Install Miniconda and create conda environments with packages installed.
  company: SciLifeLab Clinical Genomics
  license: MIT
  min_ansible_version: 1.4

  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!

  platforms:
   - name: Ubuntu
     versions:
        - all
        - lucid
        - maverick
        - natty
        - oneiric
        - precise
        - quantal
        - raring
        - saucy
        - trusty

   - name: Debian
     versions:
        - all
        - etch
        - lenny
        - squeeze
        - wheezy

  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.

  categories:
    - packaging
    - system

# List the names of roles on which this role depends.
# They will be executed first, with their defaults mixed in.
# http://www.ansibleworks.com/docs/playbooks_roles.html#role-dependencies
dependencies: []
