---
# tasks file for ansible-role-pyhton

- name: Create environment for python 2 installation
  command: "{{ ansible_env.PWD }}/{{ miniconda_home }}/conda create --yes --name py2 python=2"

- name: Create environment for python 3 installation
  command: "{{ ansible_env.PWD }}/{{ miniconda_home }}/conda create --yes --name py3 python=3"
