---
# tasks file for ansible-role-devtools

- name: Install Development Tools
  yum: 
    name: "@Development Tools"
    state: present
  become: true
  become_user: root


- name: Ensure that the required packages are present
  yum: name={{ item }} state=present
  become: true
  become_user: root
  with_items:
      - wget
      - sed
