galaxy_info:
  author: Coadunate Organization
  description: QIIME Install and Env Configuration
  company: Coadunate

  license: CC-BY

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - all
    - 5
    - 6
    - 7

dependencies:
  - coadunate.devtools
  - coadunate.python
  - coadunate.miniconda

