---

# handlers for miniconda role

- name: remove miniconda setup script
  file: name=/tmp/miniconda.sh state=absent

- name: update conda to latest version
  shell: "{{ miniconda_home }}/bin/conda update conda --yes -q executable=/bin/bash"
