---
galaxy_info:
  author: Coadunate Organization
  description: Python
  min_ansible_version: 2.0
  platforms:
  - name: Centos
    versions:
    - all
  - name: Fedora
    versions:
    - all
  galaxy_tags:
    - python

dependencies: []
