---
# necessary steps to configure the role

- name: install base condarc
  copy: src={{ item }} dest="~/.{{ item }}"
  with_items:
    - condarc
  when: miniconda_add_condarc

- name: add miniconda to the PATH
  lineinfile:
    dest: '{{ ansible_env.PWD }}/{{ miniconda_rcfile }}'
    regexp: ''
    insertafter: EOF
    line: 'export PATH={{ ansible_env.PWD }}/{{ miniconda_home }}/bin:$PATH'
    state: present
